spring.application.name=bibliotheque_quali_dev
spring.datasource.url=jdbc:mysql://localhost/bibliotheque
spring.datasource.username=bibli
spring.datasource.password=mdp123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#a corriger le user car root pas acces a la table biblio
#faut faire en sorte que tt le monde pr la base ait le user root
#et meme mdp